### PR TITLE
global: update AUTHORS

### PR DESCRIPTION
**Pull request by omelkonian**
- Adds myself to AUTHORS file.

Signed-off-by: Orestis Melkonian melkon.or@gmail.com

### CODE REVIEW

**Comment by omelkonian** [comment]
@jirikuncar ping

**Comment by jirikuncar** [comment]
@omelkonian pong `This branch is out-of-date with the base branch` ❗️

**Comment by jirikuncar** [comment]
`@omelkonian omelkonian removed their assignment 5 minutes ago` have you checked the PR before unassigning yourself?

**Comment by omelkonian** [comment]
@jirikuncar Sorry, I thought assignees on PRs are the reviewers. Rebased.

**Comment by omelkonian** [comment]
@jirikuncar ping

**Comment by jirikuncar** [comment]
LGTM

**Pull request merged**
